config/routes.rb
Rails.application.routes.draw do
  resources :songs
  resources :artists

  get 'top' => 'rock#top'

  root 'rock#roll'

end

app/models/artist.rb
class Artist < ActiveRecord::Base
	has_many :songs
	validates :name, presence: true
	validates :name, uniqueness: true
	mount_uploader :photo, PhotoUploader
end

app/models/song.rb
class Song < ActiveRecord::Base
	belongs_to :artist
	
	validates :name, :rating, :artist_id, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.songs.destroy_all
    @artist.destroy

    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:name, :rating, :photo)
    end
end

app/controllers/rock_controller.rb
class RockController < ApplicationController
  def roll
  	@songs = Song.order(rating: :desc).limit(5)
  end

  def top
  	@artists = Artist.order(rating: :desc).limit(5)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new

    if params[:id] == nil
      @artists = Artist.order(:name)
    else
      @artists = Artist.where(id: params[:id])
    end
  
  end

  # GET /songs/1/edit
  def edit
    @artists = Artist.all

  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)
    @artists = Artist.order(:name)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:name, :rating, :artist_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/rock_helper.rb
module RockHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% @artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class = "col-md-6 col-md-offset-3">
      <div class = "well">
        <div class="form-group">
          <p><%= f.text_field :name, placeholder: "Name", class: "form-control"%></p>
        </div>
        <div class="form-group">
          <p><%= f.select :rating, %w(1 2 3 4 5 6 7 8 9 10), {:include_blank => 'Rating'}, class: "form-control" %></p>
        </div>
        <div class="form-group">
          <strong>Uplaod Photo</strong>
            <%= f.file_field :photo %>
        </div>
        <div class="actions">
          <%= f.submit class: "btn btn-default" %></p>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing Artist</h1>

<%= render 'form' %>

<%= link_to 'Back', @artist %>

app/views/artists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Artists</h1>

<%= link_to new_artist_path do %>
  <i class="fa fa-plus-circle" aria-hidden="true"></i>New Artist
<% end %>

  <div class="row">
    <% @artists.each do |artist| %>
      <div class="col-md-6">
        <div class="well">
          <h2><%= artist.name %></h2>
            <%= image_tag artist.photo.url, class:"photo" %>
            <p>
              <% 10.times do |i|%>
                <% if i < artist.rating.to_i %>
                  <i class="fa fa-star yellow" aria-hidden="true"></i>
                <% else %>
                  <i class="fa fa-star" aria-hidden="true"></i>
                <% end %>
              <% end %>
            </p>
          <%= link_to artist do %>
            Show
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render 'form' %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<p>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="well">
      <h2><%= @artist.name %></h2>
      <%= image_tag @artist.photo.url, class:"photo" %>
      <p>
	      <% 10.times do |i|%>
	      	<% if i < @artist.rating.to_i %>
	      		<i class="fa fa-star yellow" aria-hidden="true"></i>
	      	<% else %>
	      		<i class="fa fa-star" aria-hidden="true"></i>
	      	<% end %>
	      <% end %>
	     </p>
	    <%= link_to new_song_path(id: @artist.id) do %>
  			<i class="fa fa-plus-circle" aria-hidden="true"></i>New Song
			<% end %>
      <%= link_to edit_artist_path(@artist) do %>
        <i class="fa fa-scissors" aria-hidden="ture"></i>Edit
      <% end %>
      <%= link_to @artist, method: :delete, data: { confirm: 'Are you sure?' } do%>
        <i class="fa fa-trash-o" aria-hidden="true"></i>Destroy
      <% end %>
    </div>
  </div>
</div>
<% @artist.songs.each do |song| %>
	<div class="row">
		<div class="col-md-12">
			<div class = "well list-well">
				<h3><%= song.name %></h3>
			</div>
		</div>
	</div>
<% end %>

<%= link_to 'Back', artists_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Top5</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Diplomata|Open+Sans:400,300,300italic,400italic,700,700italic' rel='stylesheet' type='text/css'>
</head>
<body>

    <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand">Will's Musical Taste</h3>
              <nav>
                <ul class="nav masthead-nav">
                  <li><%= link_to "Top 5 Songs", root_path %></li>
                  <li><%= link_to "Top 5 Artists", top_path %><li>
                  <li><%= link_to "Artists", artists_path %></li>
                  <li><%= link_to "Songs", songs_path %></li>
                </ul>
              </nav>
            </div>
          </div>

          <div class="inner cover">
            		<%= yield %>
          </div>

          <div class="mastfoot">
            <div class="inner">
              <p>So Tastefull. Will's Music Site &copy; 2016</p>
            </div>
          </div>

        </div>

      </div>

    </div>

</body>
</html>

app/views/rock/roll.html.erb
<h1>Top 5 Songs</h1>

  <div class = "row">
    <% @songs.each_with_index do |song, i| %>
     <div class="col-md-12">
        <div class = "well">
          <div class = "row">
            <div class = "col-md-1">
              <div class="top">
                <%= i + 1 %>
              </div>
            </div>  
            <div class = "col-md-11">            
              <h2><%= link_to song.name, song %></h2>
              <h3><%= song.artist.name %></h3>
              <p>
                <% song.rating.to_i.times do %>
                  <i class="fa fa-star yellow" aria-hidden="true"></i>
                <% end %>
                <% (10 - song.rating.to_i).times do %>
                  <i class="fa fa-star" aria-hidden="true"></i>
                <% end %>
              </p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

app/views/rock/top.html.erb
<h1>Top 5 Artists</h1>

<%= link_to new_artist_path do %>
  <i class="fa fa-plus-circle" aria-hidden="true"></i>New Artist
<% end %>

  <div class="row">
    <% @artists.each_with_index do |artist,i| %>
      <div class="col-md-12">
        <div class="well">
          <div class = "row">
            <div class = "col-md-1">
              <div class="top">
                <%= i + 1 %>                      
              </div>
            </div>
            <div class = "col-md-11">
              <h2><%= artist.name %></h2>
              <%= image_tag artist.photo.url, class:"photo" %>
                <p>
                  <% 10.times do |i|%>
                    <% if i < artist.rating.to_i %>
                      <i class="fa fa-star yellow" aria-hidden="true"></i>
                    <% else %>
                      <i class="fa fa-star" aria-hidden="true"></i>
                    <% end %>
                  <% end %>
                </p>
              <%= link_to artist do %>
                Show
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_field :name, placeholder: "Song Name", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.select :rating, %w(1 2 3 4 5 6 7 8 9 10), {:include_blank => 'Rating'}, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.select(:artist_id, @artists.collect {|a| [ a.name, a.id ] }, {:include_blank => 'Please select an artist', :selected =>  (params[:id] ||= 0) }, class: "form-control") %>
  </div>
  <div class="actions">
    <%= f.submit class: "form-control"%>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Songs</h1>

<%= link_to new_song_path do %>
  <i class="fa fa-plus-circle" aria-hidden="true"></i>New Song
<% end %>

  <div class = "row">
    <% @songs.each do |song| %>
     <div class="col-md-6">
        <div class = "well box-well">
          <h2><%= link_to song.name, song %></h2>
          <h3 id="artist-name"><%= song.artist.name %></h3>
          <p>
            <% song.rating.to_i.times do %>
              <i class="fa fa-star yellow" aria-hidden="true"></i>
            <% end %>
            <% (10 - song.rating.to_i).times do %>
              <i class="fa fa-star" aria-hidden="true"></i>
            <% end %>
          </p>
          
          <%= link_to edit_song_path(song) do %>
            <i class="fa fa-scissors" aria-hidden="true"></i>Edit
          <% end %>

          <%= link_to song, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <i class="fa fa-trash-o" aria-hidden="true"></i> Destroy
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @song.name %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @song.rating %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @song.artist_id %>
</p>

<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>